/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projekt_aplikacji;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Dzemor
 */
public class Projekt_aplikacji extends javax.swing.JFrame {

    /**
     * Creates new form Proejkt_aplikacji
     */
    public Projekt_aplikacji() {
        initComponents();
    }
    private void saveSettings(){
        try{
            FileWriter fw = new FileWriter("settings.txt");
            String plec;
            if(ms_jRadioButtonMale.isSelected()){
                plec = "Mezczyzna";
            }else if(ms_jRadioButtonFemale.isSelected()){
                plec = "Kobieta";
            }else{
                plec = "NULL";
            }
            String miejscowosc;
            if(ms_jRadioButtonCity1.isSelected()){
                miejscowosc = "10k";
            }else  if(ms_jRadioButtonCity2.isSelected()){
                miejscowosc = "10k-25k";
            }else  if(ms_jRadioButtonCity3.isSelected()){
                miejscowosc = "25k-50k";
            }else  if(ms_jRadioButtonCity4.isSelected()){
                miejscowosc = "50k-100k";
            }else if(ms_jRadioButtonCity5.isSelected()){
                miejscowosc = "100k";
            }else{
                miejscowosc = "NULL";
            }
            String zainteresowania = "";
            if(ms_jCheckBoxSport.isSelected()){
                zainteresowania += "sport;";
            }
            if(ms_jCheckBoxGames.isSelected()){
                zainteresowania += "gry;";
            }
            if(ms_jCheckBoxProgramming.isSelected()){
                zainteresowania += "prog;";
            }
            if(ms_jCheckBoxOther.isSelected()){
                zainteresowania += "inne;";
            }
            fw.write(""+plec+";"+miejscowosc+"; \n"+zainteresowania);
            fw.close();
        }catch (IOException ex) {
            System.out.println("Blad: "+ex.toString());
        }
    }
    File fileSettings  = new File("settings.txt");
    private void loadSettings(){
        try{
            Scanner sc = new Scanner(fileSettings);
            ms_buttonGroupGender.clearSelection();
            ms_buttonGroupCity.clearSelection();
            ms_jCheckBoxSport.setSelected(false);
            ms_jCheckBoxGames.setSelected(false);
            ms_jCheckBoxProgramming.setSelected(false);
            ms_jCheckBoxOther.setSelected(false);
        }catch(FileNotFoundException ex){
            System.out.println("Blad: "+ex.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ms_buttonGroupCity = new javax.swing.ButtonGroup();
        ms_buttonGroupGender = new javax.swing.ButtonGroup();
        ms_jPanelMain = new javax.swing.JPanel();
        ms_jLabelChoose = new javax.swing.JLabel();
        ms_jLabelGender = new javax.swing.JLabel();
        ms_jRadioButtonFemale = new javax.swing.JRadioButton();
        ms_jRadioButtonMale = new javax.swing.JRadioButton();
        ms_jLabelCity = new javax.swing.JLabel();
        ms_jRadioButtonCity1 = new javax.swing.JRadioButton();
        ms_jRadioButtonCity2 = new javax.swing.JRadioButton();
        ms_jRadioButtonCity3 = new javax.swing.JRadioButton();
        ms_jRadioButtonCity4 = new javax.swing.JRadioButton();
        ms_jRadioButtonCity5 = new javax.swing.JRadioButton();
        ms_jLabelHobby = new javax.swing.JLabel();
        ms_jCheckBoxProgramming = new javax.swing.JCheckBox();
        ms_jCheckBoxGames = new javax.swing.JCheckBox();
        ms_jCheckBoxSport = new javax.swing.JCheckBox();
        ms_jCheckBoxOther = new javax.swing.JCheckBox();
        ms_jButtonSave = new javax.swing.JButton();
        ms_jButtonLoad = new javax.swing.JButton();
        ms_jMenuBar = new javax.swing.JMenuBar();
        ms_jMenuFile = new javax.swing.JMenu();
        ms_jMenuItemLoad = new javax.swing.JMenuItem();
        ms_jMenuItemSave = new javax.swing.JMenuItem();
        ms_jMenuItemClose = new javax.swing.JMenuItem();
        ms_jMenuEdit = new javax.swing.JMenu();
        ms_jMenuItemFont = new javax.swing.JMenuItem();
        ms_jMenuItemColor = new javax.swing.JMenuItem();
        ms_jMenuHelp = new javax.swing.JMenu();
        ms_jMenuItemAbout = new javax.swing.JMenuItem();
        ms_jMenuItemHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projekt aplikacji");
        setResizable(false);

        ms_jLabelChoose.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ms_jLabelChoose.setText("Wybór zainteresowań");

        ms_jLabelGender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ms_jLabelGender.setText("Wybierz płeć:");

        ms_buttonGroupGender.add(ms_jRadioButtonFemale);
        ms_jRadioButtonFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jRadioButtonFemale.setText("Kobieta");

        ms_buttonGroupGender.add(ms_jRadioButtonMale);
        ms_jRadioButtonMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jRadioButtonMale.setText("Mężczyzna");

        ms_jLabelCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ms_jLabelCity.setText("Wybierz obszar w którym mieszkasz:");

        ms_buttonGroupCity.add(ms_jRadioButtonCity1);
        ms_jRadioButtonCity1.setText("Do 10 tyś");
        ms_jRadioButtonCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jRadioButtonCity1ActionPerformed(evt);
            }
        });

        ms_buttonGroupCity.add(ms_jRadioButtonCity2);
        ms_jRadioButtonCity2.setText("Od 10 do 20 tyś");
        ms_jRadioButtonCity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jRadioButtonCity2ActionPerformed(evt);
            }
        });

        ms_buttonGroupCity.add(ms_jRadioButtonCity3);
        ms_jRadioButtonCity3.setText("Od 25 do 50 tyś");

        ms_buttonGroupCity.add(ms_jRadioButtonCity4);
        ms_jRadioButtonCity4.setText("Od 50 do 100 tyś");
        ms_jRadioButtonCity4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jRadioButtonCity4ActionPerformed(evt);
            }
        });

        ms_buttonGroupCity.add(ms_jRadioButtonCity5);
        ms_jRadioButtonCity5.setText("Powyżej 100 tyś");

        ms_jLabelHobby.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ms_jLabelHobby.setText("Wybierz zainteresowanie:");

        ms_jCheckBoxProgramming.setText("Programowanie");

        ms_jCheckBoxGames.setText("Gry komputerowe");

        ms_jCheckBoxSport.setText("Sport");

        ms_jCheckBoxOther.setText("Inne");

        ms_jButtonSave.setText("Zapisz ustawienia");
        ms_jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jButtonSaveActionPerformed(evt);
            }
        });

        ms_jButtonLoad.setText("Wczytaj");
        ms_jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jButtonLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ms_jPanelMainLayout = new javax.swing.GroupLayout(ms_jPanelMain);
        ms_jPanelMain.setLayout(ms_jPanelMainLayout);
        ms_jPanelMainLayout.setHorizontalGroup(
            ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                        .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ms_jCheckBoxOther)
                            .addComponent(ms_jCheckBoxSport)
                            .addComponent(ms_jCheckBoxGames)
                            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                                .addComponent(ms_jLabelGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ms_jRadioButtonFemale)
                                .addGap(18, 18, 18)
                                .addComponent(ms_jRadioButtonMale))
                            .addComponent(ms_jLabelCity)
                            .addComponent(ms_jLabelHobby)
                            .addComponent(ms_jCheckBoxProgramming)
                            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                                .addComponent(ms_jRadioButtonCity1)
                                .addGap(18, 18, 18)
                                .addComponent(ms_jRadioButtonCity2)
                                .addGap(18, 18, 18)
                                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                                        .addComponent(ms_jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ms_jButtonLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                                        .addComponent(ms_jRadioButtonCity3)
                                        .addGap(18, 18, 18)
                                        .addComponent(ms_jRadioButtonCity4)
                                        .addGap(18, 18, 18)
                                        .addComponent(ms_jRadioButtonCity5)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms_jPanelMainLayout.createSequentialGroup()
                        .addGap(0, 220, Short.MAX_VALUE)
                        .addComponent(ms_jLabelChoose)
                        .addGap(228, 228, 228))))
        );
        ms_jPanelMainLayout.setVerticalGroup(
            ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ms_jLabelChoose)
                .addGap(18, 18, 18)
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jLabelGender)
                    .addComponent(ms_jRadioButtonMale)
                    .addComponent(ms_jRadioButtonFemale))
                .addGap(18, 18, 18)
                .addComponent(ms_jLabelCity)
                .addGap(18, 18, 18)
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jRadioButtonCity1)
                    .addComponent(ms_jRadioButtonCity2)
                    .addComponent(ms_jRadioButtonCity3)
                    .addComponent(ms_jRadioButtonCity4)
                    .addComponent(ms_jRadioButtonCity5))
                .addGap(18, 18, 18)
                .addComponent(ms_jLabelHobby)
                .addGap(18, 18, 18)
                .addComponent(ms_jCheckBoxProgramming)
                .addGap(18, 18, 18)
                .addComponent(ms_jCheckBoxGames)
                .addGap(18, 18, 18)
                .addComponent(ms_jCheckBoxSport)
                .addGap(18, 18, 18)
                .addComponent(ms_jCheckBoxOther)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jButtonLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ms_jMenuFile.setText("Plik");

        ms_jMenuItemLoad.setText("Wczytaj plik");
        ms_jMenuItemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemLoadActionPerformed(evt);
            }
        });
        ms_jMenuFile.add(ms_jMenuItemLoad);

        ms_jMenuItemSave.setText("Zapisz plik");
        ms_jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemSaveActionPerformed(evt);
            }
        });
        ms_jMenuFile.add(ms_jMenuItemSave);

        ms_jMenuItemClose.setText("Zamknj");
        ms_jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemCloseActionPerformed(evt);
            }
        });
        ms_jMenuFile.add(ms_jMenuItemClose);

        ms_jMenuBar.add(ms_jMenuFile);

        ms_jMenuEdit.setText("Edycja");

        ms_jMenuItemFont.setText("Zmień czcionkę");
        ms_jMenuItemFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemFontActionPerformed(evt);
            }
        });
        ms_jMenuEdit.add(ms_jMenuItemFont);

        ms_jMenuItemColor.setText("Zmień kolor");
        ms_jMenuItemColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemColorActionPerformed(evt);
            }
        });
        ms_jMenuEdit.add(ms_jMenuItemColor);

        ms_jMenuBar.add(ms_jMenuEdit);

        ms_jMenuHelp.setText("Pomoc");

        ms_jMenuItemAbout.setText("O programie");
        ms_jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemAboutActionPerformed(evt);
            }
        });
        ms_jMenuHelp.add(ms_jMenuItemAbout);

        ms_jMenuItemHelp.setText("Pomoc");
        ms_jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemHelpActionPerformed(evt);
            }
        });
        ms_jMenuHelp.add(ms_jMenuItemHelp);

        ms_jMenuBar.add(ms_jMenuHelp);

        setJMenuBar(ms_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ms_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ms_jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ms_jRadioButtonCity4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jRadioButtonCity4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jRadioButtonCity4ActionPerformed

    private void ms_jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jButtonSaveActionPerformed
        saveSettings();
    }//GEN-LAST:event_ms_jButtonSaveActionPerformed

    private void ms_jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jButtonLoadActionPerformed
        loadSettings();
    }//GEN-LAST:event_ms_jButtonLoadActionPerformed

    private void ms_jRadioButtonCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jRadioButtonCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jRadioButtonCity1ActionPerformed

    private void ms_jMenuItemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemLoadActionPerformed
        loadSettings();
    }//GEN-LAST:event_ms_jMenuItemLoadActionPerformed

    private void ms_jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemSaveActionPerformed
        saveSettings();
    }//GEN-LAST:event_ms_jMenuItemSaveActionPerformed

    private void ms_jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ms_jMenuItemCloseActionPerformed

    private void ms_jRadioButtonCity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jRadioButtonCity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jRadioButtonCity2ActionPerformed

    private void ms_jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemAboutActionPerformed
       JOptionPane.showMessageDialog(null,"Wykonał Mateusz Suchocki z 2 PTN");
    }//GEN-LAST:event_ms_jMenuItemAboutActionPerformed

    private void ms_jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jMenuItemHelpActionPerformed

    private void ms_jMenuItemFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemFontActionPerformed
        Font ms_czcionka = new Font("Comic Sans MS", Font.PLAIN, 36);
        ms_jLabelChoose.setFont(ms_czcionka);
    }//GEN-LAST:event_ms_jMenuItemFontActionPerformed

    private void ms_jMenuItemColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemColorActionPerformed
        Random ms_rand = new Random();
        float ms_r = ms_rand.nextFloat();
        float ms_g = ms_rand.nextFloat();
        float ms_b = ms_rand.nextFloat();
        Color ms_kolor = new Color(ms_r, ms_g, ms_b);
        ms_jPanelMain.setBackground(ms_kolor);
    }//GEN-LAST:event_ms_jMenuItemColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projekt_aplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projekt_aplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projekt_aplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projekt_aplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projekt_aplikacji().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ms_buttonGroupCity;
    private javax.swing.ButtonGroup ms_buttonGroupGender;
    private javax.swing.JButton ms_jButtonLoad;
    private javax.swing.JButton ms_jButtonSave;
    private javax.swing.JCheckBox ms_jCheckBoxGames;
    private javax.swing.JCheckBox ms_jCheckBoxOther;
    private javax.swing.JCheckBox ms_jCheckBoxProgramming;
    private javax.swing.JCheckBox ms_jCheckBoxSport;
    private javax.swing.JLabel ms_jLabelChoose;
    private javax.swing.JLabel ms_jLabelCity;
    private javax.swing.JLabel ms_jLabelGender;
    private javax.swing.JLabel ms_jLabelHobby;
    private javax.swing.JMenuBar ms_jMenuBar;
    private javax.swing.JMenu ms_jMenuEdit;
    private javax.swing.JMenu ms_jMenuFile;
    private javax.swing.JMenu ms_jMenuHelp;
    private javax.swing.JMenuItem ms_jMenuItemAbout;
    private javax.swing.JMenuItem ms_jMenuItemClose;
    private javax.swing.JMenuItem ms_jMenuItemColor;
    private javax.swing.JMenuItem ms_jMenuItemFont;
    private javax.swing.JMenuItem ms_jMenuItemHelp;
    private javax.swing.JMenuItem ms_jMenuItemLoad;
    private javax.swing.JMenuItem ms_jMenuItemSave;
    private javax.swing.JPanel ms_jPanelMain;
    private javax.swing.JRadioButton ms_jRadioButtonCity1;
    private javax.swing.JRadioButton ms_jRadioButtonCity2;
    private javax.swing.JRadioButton ms_jRadioButtonCity3;
    private javax.swing.JRadioButton ms_jRadioButtonCity4;
    private javax.swing.JRadioButton ms_jRadioButtonCity5;
    private javax.swing.JRadioButton ms_jRadioButtonFemale;
    private javax.swing.JRadioButton ms_jRadioButtonMale;
    // End of variables declaration//GEN-END:variables
}
